#Seminar 2 -- Lucram in jupyter!

In [2]:
import seaborn as sns
import numpy as np
import pandas as pd

penguins = sns.load_dataset("penguins")

#Descriere/Explorarea DataSet

In [3]:
penguins.head()
# daca are ouotput il baga automat dedesubt

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

#TitluH1
##SubtitluH2
###SubtitluH3

#INFO

In [4]:
penguins.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [5]:
penguins.select_dtypes(include="number").mean()

bill_length_mm         43.921930
bill_depth_mm          17.151170
flipper_length_mm     200.915205
body_mass_g          4201.754386
dtype: float64

In [7]:
penguins.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [10]:
penguins[penguins.columns[2:]].groupby("sex").aggregate("mean")

        bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
sex
Female       42.096970      16.425455         197.363636  3862.272727
Male         45.854762      17.891071         204.505952  4545.684524

In [21]:
# toti pinguinii sub 4kg sunt fete restul baieti - V1

# loc -- in liniile in care se respecta conditie, valoarea inlocuita
penguins.loc[penguins["body_mass_g"] <= 4000,"sex"]="Female"
penguins.loc[penguins["body_mass_g"] > 4000,"sex"]="Male"

penguins.head()

In [23]:
# toti pinguinii sub 4kg sunt fete restul baieti - V2

penguins["sex"]=np.where(
    penguins["sex"].isna(),
    np.where(
        penguins["body_mass_g"]<4000,
        "Female",
        "Male"),
    penguins["sex"])

penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Female,Female,39.1,18.7,181.0,3750.0,Female
1,Female,Female,39.5,17.4,186.0,3800.0,Female
2,Female,Female,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,Male
4,Female,Female,36.7,19.3,193.0,3450.0,Female

#de cautat cum fac sa fac cu IF direct ca sa nu mai fac ciudateniile astea aici!!!

In [24]:
penguins=penguins.dropna()
penguins.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [ ]:
penguins["bill_area"]=penguins["bill_depth_mm"] * penguins["bill_length_mm"]
penguins.head()